---
title: "Stability of $\\log \\det M$ and $\\partial\\log\\det M$"
abstract: "I show my efforts in stabilizing the $\\log\\det M$ and $\\partial\\log\\det M$ routines for large $\beta$"
author:
  name: Thomas Luu
  affiliation: IAS-4, FZJ & HISKP, Uni. Bonn
  email: t.luu@fz-juelich.de
format:
  revealjs:
    slide-number: true
    incremental: false
from: markdown+emoji
---


## Expressions
:::{style='font-size:70%'}

$$ \log\det M[\phi]=\log\det(\mathbb{1}_{N_x}+\underbrace{F_k(N_t-1).F_k(N_t-2)\ldots F_k(0)}_{\mathrm{``sausage\ 1"}})\quad;\quad F_k(t)\equiv \underbrace{e^{\tilde\kappa}}_{\mathrm{dense}}. \underbrace{e^{i\phi_t(x)}}_{\mathrm{diagonal}} \quad;\quad \tilde\kappa=\kappa\frac{\beta}{N_t}$$

$$\partial_{\phi_t(x)} \log\det M[\phi]= \left\{f_k(t+1).f_k(t+2)\ldots f_k(N_t-1).[\mathbb{1}_{N_x}+\underbrace{f_k(0)\ldots f_k(N_t-1)}_{\mathrm{``sausage\ 2"}}]^{-1}.f_k(0)\ldots f_k(t) \right\}_{x,x} $$
$$ f_k(t)=F_k^{-1}(k)=e^{-i\phi_t(x)}.e^{-\tilde\kappa}$$

:::{.callout-note}
## Note:  $[\mathrm{sausage\ 2}]^{-1}=\mathrm{sausage\ 1}$
:::

:::

## Stabilizing $\log\det M$

:::{style='font-size:70%'}

+ Express $F_k(t)=e^{\tilde\kappa}.e^{i\phi_t}=U.\underbrace{D_{\tilde\kappa}}_{\mathrm{diagonal}}.\underbrace{V.e^{i\phi_t}}_{\equiv V(t)}\equiv U.D_{\tilde\kappa}.V(t)$
  - Note that $U.V=\mathbb{1}_{N_x}$ ***and*** $V(t).V^\dagger (t)=\mathbb{1}_{N_x}$

+ Initial SVD of sausage
  $$ F_k(N_t-1).F_k(N_t-2)\ldots F_k(0)=U.\underbrace{D_{\tilde\kappa}.V(N_t-1).U.D_{\tilde\kappa}}_{=u.d.v}.V(N_t-2)\ldots U.D_{\tilde\kappa}.V(0)$$

+ Recursively perform SVD^[One can also do a different decomposition, like QR.  For these notes I only assume SVD. Only slight changes would be required for a different decomposition.] on expressions of the form $D.V(t).U.D =u.d.v$ until one arrives at^[This method draws inspiration from [C.Bauer, SciPost Phys. Core 2, 011 (2020)](https://scipost.org/SciPostPhysCore.2.2.011) and Johann's notes]
  $$ \mathbb{1}_{N_x}+u.d.v = u.(\underbrace{u^\dagger v^\dagger+d}_{q.r}).v \quad\quad (=\mathbb{1}_{N_x}+\mathrm{sausage})$$

+ Final expression for $\log\det M$
  $$ \log\det M = \log\det\left(u.q.r.v\right) =\log\det(u.q)+\log\det(v)+\sum_x\log r_{x,x}$$
:::

## Stabilizing $\partial\log\det M$

:::{style='font-size:80%'}

+ Key feature here is the construction of $[\mathbb{1}+f_k(0)\ldots f_k(N_t-1)]^{-1}$

+ Express $f_k(t)=e^{-i\phi_t}.e^{-\tilde\kappa}=\underbrace{e^{-i\phi_t}.U}_{\equiv U(t)}.\underbrace{D_{\tilde\kappa}}_{\mathrm{diagonal}}.V\equiv U(t).D_{\tilde\kappa}.V$ 

+ As before, we construct the sausage via recursive decomposition 
  $$ \mathbb{1}+f_k(0)\ldots f_k(N_t-1)=\mathbb{1}+u.d.v=u.(\underbrace{u^\dagger v^\dagger+d}_{q.r}).v =u.q.r.v$$

+ Then we have
  $$ [\mathbb{1}+f_k(0)\ldots f_k(N_t-1)]^{-1}=v^\dagger.r^{-1}.q^\dagger.u^\dagger $$
  
+ Though there is an inverse to calculate, $r^{-1}$, this matrix is triangular and so this should not be that bad


:::

## Strategy for calculating $\partial_{\phi_t}\log\det M$ {#sec-pidot-1}

:::{style='font-size:80%'}

+ Assume we can calculate $\mathcal{N}_k\equiv[f_k(0)\ldots f_k(N_t-1)].[\mathbb{1}+f_k(0)\ldots f_k(N_t-1)]^{-1}$  
   
  $=\dot\pi(N_t-1)$

+ Then 
  $$
  \begin{align}
  \dot\pi(0)&=f_k(0)^{-1}.\mathcal{N}_k.f_k(0) = F_k(0).\mathcal{N}_k.f_k(0)\\
  \dot\pi(1)&=f_k(1)^{-1}.\dot\pi(0).f_k(1)=F_k(1).\dot\pi(0).f_k(1)\\
  \vdots\\
  \dot\pi(t)&=f_k(t)^{-1}.\dot\pi(t-1).f_k(t)=F_k(t).\dot\pi(t-1).f_k(t)\\
  \vdots\\
  \dot\pi(N_t-2)&=f_k(n_t-2)^{-1}.\dot\pi(N_t-3).f_k(N_t-2)=F_k(N_t-2).\dot\pi(N_t-3).f_k(N_t-2)
  \end{align}
  $$
  
:::{.callout-note}
## The calculation of $\dot\pi(t)$ can be done iteratively, since it only depends on the previous $\dot\pi(t-1)$.  Furthermore, I suspect that it is very stable (i.e. doesn't need any decompositions) since we are always multiplying matrices with matrix elements of $\mathcal{O}(1)$.
:::

:::{.callout-warning}
## But this assumes that we have calculated $\mathcal{N}_k$ accurately!!!
:::

:::{.callout-note}
## Note, we do have a stable way of calculating $\mathcal{N}_k$.  However(!!!), the iterative method proposed above is not stable, even with decompositions :angry:
:::
  
:::

## Testing in the non-interacting limit on the 4-site hex (w/ PBCs)

:::{style='font-size:80%'}

+ In the non-interacting limit we have $\phi_t(x)=0\quad\forall\  x,t$.

+ In this limit we have analytical results

:::{style='font-size:60%'}
<!--
$$
\mathrm{sausage}=\mathrm{sausage}^{-1}=
\left(
\begin{array}{cccc}
 \cosh (\beta ) \cosh (2 \beta ) & 2 \sinh (\beta ) \cosh ^2(\beta ) & 2 \sinh ^2(\beta )
   \cosh (\beta ) & \sinh (\beta ) \cosh (2 \beta ) \\
 2 \sinh (\beta ) \cosh ^2(\beta ) & \cosh (\beta ) \cosh (2 \beta ) & \sinh (\beta )
   \cosh (2 \beta ) & 2 \sinh ^2(\beta ) \cosh (\beta ) \\
 2 \sinh ^2(\beta ) \cosh (\beta ) & \sinh (\beta ) \cosh (2 \beta ) & \cosh (\beta )
   \cosh (2 \beta ) & 2 \sinh (\beta ) \cosh ^2(\beta ) \\
 \sinh (\beta ) \cosh (2 \beta ) & 2 \sinh ^2(\beta ) \cosh (\beta ) & 2 \sinh (\beta )
   \cosh ^2(\beta ) & \cosh (\beta ) \cosh (2 \beta ) \\
\end{array}
\right)
$$
-->

$$
\mathrm{sausage}=
\left(
\begin{array}{cccc}
 \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\
 \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
 \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\
 \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
\end{array}
\right).
\mathrm{diag}\left(e^{3\beta},e^{\beta},e^{-\beta},e^{-3\beta}\right).
\left(
\begin{array}{cccc}
 \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
 -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
 \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
 -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
\end{array}
\right)
$$

<!--
$$ [1+\mathrm{sausage}]^{-1}
=
\left(
\begin{array}{cccc}
 \frac{1}{2} & -\sinh \left(\frac{\beta }{2}\right)\cosh (\beta )
   \text{sech}\left(\frac{3 \beta }{2}\right) & 0 & -\frac{1}{2} \sinh \left(\frac{\beta
   }{2}\right) \text{sech}\left(\frac{3 \beta }{2}\right) \\
 -\sinh \left(\frac{\beta }{2}\right)\cosh (\beta ) \text{sech}\left(\frac{3 \beta
   }{2}\right) & \frac{1}{2} & -\frac{1}{2} \sinh \left(\frac{\beta }{2}\right)
   \text{sech}\left(\frac{3 \beta }{2}\right) & 0 \\
 0 & -\frac{1}{2} \sinh \left(\frac{\beta }{2}\right) \text{sech}\left(\frac{3 \beta
   }{2}\right) & \frac{1}{2} & -\sinh \left(\frac{\beta }{2}\right)\cosh (\beta )
   \text{sech}\left(\frac{3 \beta }{2}\right) \\
 -\frac{1}{2} \sinh \left(\frac{\beta }{2}\right) \text{sech}\left(\frac{3 \beta
   }{2}\right) & 0 & -\sinh \left(\frac{\beta }{2}\right)\cosh (\beta )
   \text{sech}\left(\frac{3 \beta }{2}\right) & \frac{1}{2} \\
\end{array}
\right)
$$
-->

$$
[1+\mathrm{sausage}]^{-1}=
\left(
\begin{array}{cccc}
 \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\
 \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
 \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\
 \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
\end{array}
\right).
\mathrm{diag}\left(\frac{1}{1+e^{3\beta}},\frac{1}{1+e^{\beta}},\frac{1}{1+e^{-\beta}},\frac{1}{1+e^{-3\beta}}\right).
\left(
\begin{array}{cccc}
 \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
 -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
 \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
 -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
\end{array}
\right)
$$

<!--
$$
\frac{\mathrm{sausage}}{1+\mathrm{sausage}}=
\left(
\begin{array}{cccc}
 \frac{1}{2} & \frac{\cosh (\beta ) \tanh \left(\frac{\beta }{2}\right)}{2 \cosh (\beta
   )-1} & 0 & \frac{1}{2} \sinh \left(\frac{\beta }{2}\right) \text{sech}\left(\frac{3
   \beta }{2}\right) \\
 \frac{\cosh (\beta ) \tanh \left(\frac{\beta }{2}\right)}{2 \cosh (\beta )-1} &
   \frac{1}{2} & \frac{1}{2} \sinh \left(\frac{\beta }{2}\right) \text{sech}\left(\frac{3
   \beta }{2}\right) & 0 \\
 0 & \frac{1}{2} \sinh \left(\frac{\beta }{2}\right) \text{sech}\left(\frac{3 \beta
   }{2}\right) & \frac{1}{2} & \frac{\cosh (\beta ) \tanh \left(\frac{\beta
   }{2}\right)}{2 \cosh (\beta )-1} \\
 \frac{1}{2} \sinh \left(\frac{\beta }{2}\right) \text{sech}\left(\frac{3 \beta
   }{2}\right) & 0 & \frac{\cosh (\beta ) \tanh \left(\frac{\beta }{2}\right)}{2 \cosh
   (\beta )-1} & \frac{1}{2} \\
\end{array}
\right)
$$
-->

$$
\frac{\mathrm{sausage}}{1+\mathrm{sausage}}=
\left(
\begin{array}{cccc}
 \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\
 \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
 \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\
 \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
\end{array}
\right).
\mathrm{diag}\left(\frac{e^{3\beta}}{1+e^{3\beta}},\frac{e^{\beta}}{1+e^{\beta}},\frac{e^{-\beta}}{1+e^{-\beta}},\frac{e^{-3\beta}}{1+e^{-3\beta}}\right).
\left(
\begin{array}{cccc}
 \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
 -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
 \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
 -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
\end{array}
\right)
$$ {#eq-Nk}

:::

:::

---

### Non-interacting Sausage w/ $\beta=50$ and $N_t=128$

:::{style='font-size:80%'}

+ Exact

:::{style='font-size:80%'}
  $$ 
  	\begin{pmatrix}
\frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
-\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
-\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2}
		\end{pmatrix}
	.
	\mathrm{diag}
	\begin{pmatrix}
	1.39370958066638\times 10^{65}\\
	5.18470552858707\times 10^{21}\\
	1.92874984796392\times 10^{-22}\\
	7.17509597316441\times 10^{-66}
	\end{pmatrix}
	.
\begin{pmatrix}
\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2}
	\end{pmatrix}
	$$
:::
	
+ Recursive SVD (**NSL**)

:::{style='font-size:60%'}
  $$
  \begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5 \\
  -0.5 & -0.500000000000001 & 0.499999999999999 & 0.5 \\
   0.5 & -0.5 & -0.5 & 0.499999999999999 \\
  -0.5 & 0.500000000000001 & -0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   1.39370958066639\times 10^{65}\\  5.18470552858687\times 10^{21}\\ 1.92874984796384\times 10^{-22}\\ 7.17509597316446\times 10^{-66}
   \end{pmatrix}
   .
  \begin{pmatrix}
   0.5 & -0.5 & 0.5 & -0.5 \\
   0.5 & -0.500000000000001 & -0.5 & 0.5 \\
   0.5 & 0.5 & -0.5 & -0.5 \\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
   $$
   
:::

:::{.callout-tip}
## Have pretty good agreement, IMO  :sunglasses:
:::

+ Brute force multiplication (no recursive SVD), then final SVD

:::{style='font-size:40%'}
  $$
  \begin{pmatrix}
   -0.5 & -0.849353925217068 & 0.169022152495865 & -0.00542417588419609 \\
    0.5 & -0.19754031043597 & 0.463838074957114 & -0.704153439225386 \\
   -0.5 & 0.209405216705662 & -0.449596032942532 & -0.709938632825959 \\
    0.5 & -0.442408398075436 & -0.744411955403781 & -0.0112093694847706
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   1.39370958066641\times 10^{65} \\ 2.11869866931353 10^{49} \\ 5.42566850332524\times 10^{48} \\ 1.50966203630934\times 10^{46}
   \end{pmatrix}
   .
  \begin{pmatrix}
   -0.5 & 0.5 & -0.5 & 0.5 \\
   -0.825084952583131 & -0.468695364415219 & 0.312457050729913 & -0.0439325374379993 \\
   -0.253624193847406 & 0.364936301964171 & -0.243525197216923 & -0.862085693028499 \\
    0.0700684616367838 & -0.630195327564716 & -0.770107829962547 & -0.0698440407610477
   \end{pmatrix}
   $$
   
:::

:::

---

### Non-interacting $[1+\mathrm{sausage}]^{-1}$ w/ $\beta=50$ and $N_t=128$

:::{style='font-size:80%'}

+ Exact

:::{style='font-size:80%'}
  $$ 
  	\begin{pmatrix}
\frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
-\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
-\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2}
		\end{pmatrix}
	.
	\mathrm{diag}
	\begin{pmatrix}
	7.17509597316441\times 10^{-66}\\
	1.92874984796392\times 10^{-22}\\
	1.00000000000000 \\
	1.00000000000000
	\end{pmatrix}
	.
\begin{pmatrix}
\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2}
	\end{pmatrix}
	$$
:::
	
+ Recursive SVD (**NSL**)

:::{style='font-size:60%'}
  $$
  \begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5 \\
  -0.5 & -0.500000000000001 & 0.5 & 0.5 \\
   0.5 & -0.5 & -0.5 & 0.5 \\
  -0.5 & 0.5 & -0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   -7.17509597316435\times 10^{-66} \\  -1.92874984796399\times 10^{-22} \\  -1 \\ 1
   \end{pmatrix}
   .
  \begin{pmatrix}
   -0.5 & 0.5 & -0.5 & 0.5 \\
   -0.5 & 0.500000000000001 & 0.5 & -0.500000000000001 \\
   -0.5 & -0.5 & 0.5 & 0.5 \\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
   $$
   
:::

:::{.callout-tip}
## Again have pretty good agreement, IMO  :sunglasses:
The minus signs that occur in **NSL** are due to the QR routine.  This is not an issue.
:::

+ Brute force multiplication (no recursive SVD), inversion, then final SVD

:::{style='font-size:40%'}
  $$
  \begin{pmatrix}
   -0.131488689031133&  0.0727976143127557&  0.852884067155229&  -0.5\\
 -0.403848776439975&  -0.708539157157157&  0.291339026810625&  0.499999999999999\\
 -0.761690587907368&  -0.0845399854681019&  -0.403336632542077&  -0.5\\
 -0.489330500498526&  0.696796786001809&  0.158208407802528&  0.500000000000001
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   5.39661293455092\times 10^{-48}\\ 1.32689109205208\times 10^{-49}\\ 6.84325412537475\times 10^{-50}\\ 1.080760332645\times 10^{-64}
   \end{pmatrix}
   .
  \begin{pmatrix}
   -0.0016914112485547&  -0.686396012976889&  -0.726049744616038&  -0.0413451428877044\\
0.038085876745577&  -0.429991450595958&  0.359302985896034&  0.82738031323757\\
0.865185878941923&  0.306541784727326&  -0.306191333432513&  0.252452760782085\\
-0.5&  0.5&  -0.5&  0.5
   \end{pmatrix}
   $$
   
:::

:::

---

### Non-interacting $\frac{\mathrm{sausage}}{1+\mathrm{sausage}}$ w/ $\beta=50$ and $N_t=128$

:::{style='font-size:80%'}

+ Exact

:::{style='font-size:80%'}
  $$ 
  	\begin{pmatrix}
\frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
-\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
-\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & \frac{1}{2}
		\end{pmatrix}
	.
	\mathrm{diag}
	\begin{pmatrix}
	1.00000000000000\\
	1.0000000000000\\
	1.92874984796392\times 10^{-22}\\
	7.17509597316441\times 10^{-66}
	\end{pmatrix}
	.
\begin{pmatrix}
\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2}
	\end{pmatrix}
	$$
:::
	
+ Recursive SVD (**NSL**)

:::{style='font-size:40%'}
$$
\begin{pmatrix}
   -0.5 & -0.5 & -0.5 & 0.5 \\
0.5 & 0.500000000000001 & -0.499999999999999 & 0.5 \\
-0.5 & 0.5 & 0.5 & 0.499999999999999 \\
0.5 & -0.500000000000001 & 0.5 & 0.5
   \end{pmatrix}
.
   \mathrm{diag}
   \begin{pmatrix}
   1.09412645109981\times 10^{+49}\\ 814046.705093647\\ 1.6753732782182\times 10^{-28}\\ 9.27417303855349\times 10^{-115}
   \end{pmatrix}
   .
  \begin{pmatrix}
   -0.707106781186548 & -0.707106781186547 & 8.52392548729562\times 10^{-17} & -4.67082681552994\times 10^{-16} \\
-6.1421537249124\times 10^{-07} & 6.14215372144703\times 10^{-07} & 0.707107395401386 & 0.707106166970642 \\
0.499999999999623 & -0.499999999999623 & -0.499999131367913 & 0.500000868631333 \\
-0.5 & 0.5 & -0.5 & 0.5
   \end{pmatrix}
$$
   
:::

:::{.callout-tip}
## Now we ***don't*** have good agreement :worried:
:::

:::

--- 

### Where does it go wrong?

:::{style='font-size:80%'}

+ Consider the construction of $\frac{\mathrm{sausage}}{1+\mathrm{sausage}}=\mathcal{N}_k$

:::{style='font-size:30%'}
$$
\begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5 \\
  -0.5 & -0.500000000000001 & 0.499999999999999 & 0.5 \\
   0.5 & -0.5 & -0.5 & 0.499999999999999 \\
  -0.5 & 0.500000000000001 & -0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   1.39370958066639\times 10^{65}\\  5.18470552858687\times 10^{21}\\ 1.92874984796384\times 10^{-22}\\ 7.17509597316446\times 10^{-66}
   \end{pmatrix}
   .
   \underbrace{
  \begin{pmatrix}
   0.5 & -0.5 & 0.5 & -0.5 \\
   0.5 & -0.500000000000001 & -0.5 & 0.5 \\
   0.5 & 0.5 & -0.5 & -0.5 \\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
   .
  \begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5 \\
  -0.5 & -0.500000000000001 & 0.5 & 0.5 \\
   0.5 & -0.5 & -0.5 & 0.5 \\
  -0.5 & 0.5 & -0.5 & 0.5
   \end{pmatrix}
   }_
   {
   v.u
   }
   .
   \mathrm{diag}
   \begin{pmatrix}
   -7.17509597316435\times 10^{-66} \\  -1.92874984796399\times 10^{-22} \\  -1 \\ 1
   \end{pmatrix}
   .
  \begin{pmatrix}
   -0.5 & 0.5 & -0.5 & 0.5 \\
   -0.5 & 0.500000000000001 & 0.5 & -0.500000000000001 \\
   -0.5 & -0.5 & 0.5 & 0.5 \\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
$$

<!--
$$
= 
\begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5 \\
  -0.5 & -0.500000000000001 & 0.499999999999999 & 0.5 \\
   0.5 & -0.5 & -0.5 & 0.499999999999999 \\
  -0.5 & 0.500000000000001 & -0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   1.39370958066639\times 10^{65}\\  5.18470552858687\times 10^{21}\\ 1.92874984796384\times 10^{-22}\\ 7.17509597316446\times 10^{-66}
   \end{pmatrix}
   .
  \begin{pmatrix}
   1 & 3.08148791101958\times 10^{-32} & 5.55111512312578\times 10^{-17} & 5.55111512312578\times 10^{-17}\\
3.08148791101958\times 10^{-32} & 1 & 2.77555756156288\times 10^{-17} & -1.94289029309402\times 10^{-16}\\
5.55111512312578\times 10^{-17} & 2.77555756156288\times 10^{-17} & 1 & -2.22044604925031\times 10^{-16}\\
1.11022302462516\times 10^{-16} & -1.94289029309402\times 10^{-16} & -3.05311331771918\times 10^{-16} & 1
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   -7.17509597316435\times 10^{-66} \\  -1.92874984796399\times 10^{-22} \\  -1 \\ 1
   \end{pmatrix}
   .
  \begin{pmatrix}
   -0.5 & 0.5 & -0.5 & 0.5 \\
   -0.5 & 0.500000000000001 & 0.5 & -0.500000000000001 \\
   -0.5 & -0.5 & 0.5 & 0.5 \\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
$$
-->
   
:::

+ The product $v.u$ ***should*** be $\mathbb{1}$, and it is up to machine precision: 

:::{style='font-size:50%'}

$$v.u = \begin{pmatrix}
   1 & \mathcal{O}(10^{-32}) & 5.55111512312578\times 10^{-17} & 5.55111512312578\times 10^{-17}\\
\mathcal{O}(10^{-32}) & 1 & 2.77555756156288\times 10^{-17} & -1.94289029309402\times 10^{-16}\\
5.55111512312578\times 10^{-17} & 2.77555756156288\times 10^{-17} & 1 & -2.22044604925031\times 10^{-16}\\
1.11022302462516\times 10^{-16} & -1.94289029309402\times 10^{-16} & -3.05311331771918\times 10^{-16} & 1
   \end{pmatrix} $$
   
:::

+ But because of the large terms in the diagonal matrix, we have

:::{style='font-size:40%'}

$$
\mathrm{diag}
   \begin{pmatrix}
   1.39370958066639\times 10^{65}\\  5.18470552858687\times 10^{21}\\ 1.92874984796384\times 10^{-22}\\ 7.17509597316446\times 10^{-66}
   \end{pmatrix}
   .v.u
=
\begin{pmatrix}
1.39370958066639\times 10^{65} & \color{red} {4.29469922429565\times 10^{33}} & \color{red} {7.7366423304825\times 10^{48}} & \color{red} {7.7366423304825\times 10^{48}}\\
\color{red} {1.59766074085368\times 10^{-10}} & 5.18470552858687\times 10^{21} & \color{red} {143904.486343462} & \color{red} {-1007331.40440424}\\
1.07067124497586\times 10^{-38} & 5.35335622487929\times 10^{-39} & 1.92874984796384\times 10^{-22} & -4.28268497990344\times 10^{-38}\\
7.96595675330243\times 10^{-82} & -1.39404243182793\times 10^{-81} & -2.19063810715817\times 10^{-81} & 7.17509597316446\times 10^{-66}
\end{pmatrix}
$$
:::

+ $\color{red} {\mathrm{Red}}$ matrix elements are bad!

:::

---

### Trying to fix this problem. . .

:::{style='font-size:80%'}

+ Changing order of multiplication of matrices (Finn's idea)
  
  Nope! :angry:
  
+ Do a QR instead of SVD (my idea)

  :::{style='font-size:40%'}
  $$
  \begin{pmatrix}
   -0.5 & -0.5 & -0.5 & 0.5 \\
   0.5 & 0.500000000000001 & -0.499999999999999 & 0.5 \\
   -0.5 & 0.5 & 0.5 & 0.499999999999999 \\
   0.5 & -0.500000000000001 & 0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   1\\ 1\\ 1.92874984796384\times10^{-22}\\ 7.17509597316447\times 10^{-66}
   \end{pmatrix}
   .
   \begin{pmatrix}
   -7.7366423304825\times 10^{48} & -7.7366423304825\times 10^{48} & 8.49275397514119\times 10^{32} & -5.4021995960771\times 10^{33} \\
   431712.959030387 & 431713.959030387 & 575618.445373849 & 575617.445373849 \\
   -0.5 & -0.5 & 0.5 & 0.5\\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
  $$
   
  :::
  Better but no cigar! :angry:
  
+ Build sausage as before, but with $[\mathbb{1}+\mathrm{sausage}]^{-1}$ as "starting seed" (Johann's idea)
 
  :::{style='font-size:60%'}
  $$
  f_k(0)\ldots f_k(N_t-2).f_k(N_t-1).[\mathbb{1}+f_k(0)\ldots f_k(N_t-1)]^{-1}
  = U.D_k.V(0)\ldots U.D_k.V(N_t-2).U.\underbrace{D_k.V(N_t-1).U_I.D_I}_{u.d.v}.V_I
  $$
  :::
  :::{style='font-size:40%'}
  $$
  =
  \begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5\\
-0.5 & -0.5 & 0.499999999999999 & 0.5\\
0.5 & -0.5 & -0.5 & 0.5\\
-0.5 & 0.5 & -0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   1.80547769569257\times 10^{48}\\ 1211923.11529062 \\ 7.39352750118232\times 10^{-24} \\ 1.53005593457498\times 10^{-113}
   \end{pmatrix}
   .
   \begin{pmatrix}
   0.61270698544548 & 0.61270698544548 & -0.352973299254082 & -0.352973299254083\\
 -0.275314527954757 & -0.422901325313383 & -0.679790695854783 & -0.532203898496157\\
 -0.546618752590289 & 0.442430355010252 & 0.404097092099114 & -0.584952015501428\\
 -0.5 & 0.5 & -0.5 & 0.5
   \end{pmatrix}
  $$
  :::
  
  Nope! :angry:
  
+ Any other ideas?

:::

---

### My one idea that "works"

:::{style='font-size:80%'}

+ I "chop" the unitary matrix $v.u$ 
  - Consider relative size of off-diagonal matrix element $m_{ij}$ to diagonal matrix element $m_{ii}$: $\frac{m_{ij}}{m_{ii}}$
  - If this ratio is less than some (user-defined) tolerance (e.g. $10^{-15}$), I set it exactly zero

  :::{style='font-size:50%'}

  $$\mathrm{chop}(v.u) =\mathrm{chop}\begin{pmatrix}
   1 & \mathcal{O}(10^{-32}) & 5.55111512312578\times 10^{-17} & 5.55111512312578\times 10^{-17}\\
\mathcal{O}(10^{-32}) & 1 & 2.77555756156288\times 10^{-17} & -1.94289029309402\times 10^{-16}\\
5.55111512312578\times 10^{-17} & 2.77555756156288\times 10^{-17} & 1 & -2.22044604925031\times 10^{-16}\\
1.11022302462516\times 10^{-16} & -1.94289029309402\times 10^{-16} & -3.05311331771918\times 10^{-16} & 1
   \end{pmatrix}
   =
   \begin{pmatrix}
   1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 &0 & 1
   \end{pmatrix}
  $$
   
  :::

+ I apply this "chop" at only one place:

  :::{style='font-size:40%'}
  $$
\begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5 \\
  -0.5 & -0.500000000000001 & 0.499999999999999 & 0.5 \\
   0.5 & -0.5 & -0.5 & 0.499999999999999 \\
  -0.5 & 0.500000000000001 & -0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   1.39370958066639\times 10^{65}\\  5.18470552858687\times 10^{21}\\ 1.92874984796384\times 10^{-22}\\ 7.17509597316446\times 10^{-66}
   \end{pmatrix}
   .
   \mathrm{chop}(v.u)
   .
   \mathrm{diag}
   \begin{pmatrix}
   -7.17509597316435\times 10^{-66} \\  -1.92874984796399\times 10^{-22} \\  -1 \\ 1
   \end{pmatrix}
   .
  \begin{pmatrix}
   -0.5 & 0.5 & -0.5 & 0.5 \\
   -0.5 & 0.500000000000001 & 0.5 & -0.500000000000001 \\
   -0.5 & -0.5 & 0.5 & 0.5 \\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
$$
  
  :::
  
+ This leads to

  :::{style='font-size:40%'}
  $$
  =
  \begin{pmatrix}
   0.5 & 0.5 & 0.5 & 0.5 \\
-0.5 & -0.500000000000001 & 0.499999999999999 & 0.5 \\
0.5 & -0.5 & -0.5 & 0.499999999999999 \\
-0.5 & 0.500000000000001 & -0.5 & 0.5
  \end{pmatrix}
   .
  \mathrm{diag}
  \begin{pmatrix}
   1 \\ 1 \\ 1.92874984796384\times 10^{-22} \\ 7.17509597316447\times 10^{-66}
  \end{pmatrix}
   .
  \begin{pmatrix}
   0.5 & -0.5 & 0.5 & -0.5 \\
0.5 & -0.500000000000001 & -0.5 & 0.500000000000001 \\
0.5 & 0.5 & -0.5 & -0.5 \\
0.5 & 0.5 & 0.5 & 0.5
  \end{pmatrix}
  $$
  :::
  
:::{.callout-tip}
## Now we once again have good agreement :sunglasses:
:::

:::{.callout-warning}
## If you don't like this solution, please suggest another!!!
:::

:::

##  I ask for a solution, and Johann delivers!

:::{style='font-size:80%'}

+ As usual, Johann comes to the rescue^[Why isn't he my boss already???]
  - Johann points out the following (in hindsight obvious) fact
  
    :::{style='font-size:80%'}
    $$
    \begin{align}
    [f_k(0)\ldots f_k(N_t-1)].[\mathbb{1}+f_k(0)\ldots f_k(N_t-1)]^{-1}
    =&
    [\mathbb{1}+f^{-1}_k(N_t-1)\ldots f^{-1}_k(0)]^{-1}\\
    =&
    [\mathbb{1}+F_k(N_t-1)\ldots F_k(0)]^{-1}
    \end{align}
    $$
    :::
	
  - @eq-Nk agrees with this result
  
+ Recursive SVD (**NSL**)

:::{style='font-size:60%'}
  $$
  \begin{pmatrix}
   0.5 & -0.5 & 0.5 & -0.5\\
   0.5 & -0.500000000000001 & -0.5 & 0.5\\
   0.5 & 0.5 & -0.5 & -0.5 \\
   0.5 & 0.5 & 0.5 & 0.5
   \end{pmatrix}
   .
   \mathrm{diag}
   \begin{pmatrix}
   -7.17509597316435\times 10^{-66} \\
   -1.92874984796399\times 10^{-22} \\
   -1 \\
    1
   \end{pmatrix}
   .
  \begin{pmatrix}
  -0.5 & -0.5 & -0.5 & -0.5\\
   0.5 & 0.500000000000001 & -0.5 & -0.500000000000001\\
  -0.5 & 0.5 & 0.5 & -0.5\\
   -0.5 & 0.5 & -0.5 & 0.5
   \end{pmatrix}
   $$
   
:::

:::{.callout-tip}
## Yes!!!, we now have good agreement and ***w/o chopping!*** :sunglasses:
:::

:::

## Another strategy for calculating forces {#sec-pidot-2}

:::{style='font-size:75%'}

+ Johann points out another strategy for calculating forces that should be more stable than that proposed in @sec-pidot-1

+ Given^[Remember that $F_k(t)=f^{-1}_k(t)$!]
  $$
  \dot\pi(N_t-1)=\left[\mathbb{1}+F_k(N_t-1)\ldots F_k(0)\right]^{-1}\equiv\left[\mathbb{1}+\mathcal{F}(N_t-1)\right]^{-1}
  $$
  it is easy to show that
  
  :::{style='font-size:80%'}
  $$
  \begin{align}
  \dot\pi(0)=F_k(0).\dot\pi(N_t-1).f_k(0)=\left[\mathbb{1}+F_k(0)F_k(N_t-1)\ldots F_k(0)f_k(0)\right]^{-1}
  &=\left[\mathbb{1}+F_k(0).\mathcal{F}(N_t-1).f_k(0)\right]^{-1}\\
  &\equiv \left[\mathbb{1}+\mathcal{F}(0)\right]^{-1}
  \end{align}
  $$
  :::
  
+ This is generalizable 
  $$ 
  \dot\pi(t)=\left[\mathbb{1}+\mathcal{F}(t)\right]^{-1}
  $$
  where
  
  :::{style='font-size:80%'}
  $$
  \mathcal{F}(t)=F_k(t).\mathcal{F}(t-1).f_k(t) = \overbrace{F_k(t).F_k(t-1)\ldots F_k(0).F_k(N_t-1).F_k(N_t-2)\ldots F_k(t+1)}^{N_t\ \mathrm{terms}}
  $$
  :::
  
+ The terms $\mathcal{F}(t)$ can be solved iteratively (though it remains to be seen if this is stable)

:::

## Benchmarking the force term

:::{style='font-size:80%'}

+ It can be shown that $\dot\pi(t)_{x,x}=\frac{i}{2}\quad\forall\ x,t$ in the non-interacting limit

:::{.r-stack}
Values of $\dot\pi(t)$ w/ $\beta=50$, $N_t=64$
:::


| $(t,x)$                         | direct                             | SVD                  | QR                   |
|:-------------------------------:|:----------------------------------:|:--------------------:|:--------------------:|
| $(0,0)$                         | $-0.534390616502179i$              | $0.500000000000001i$ | $0.500000000000001i$ |
| $(\frac{N_t}{2},\frac{N_x}{2})$ | $6.66133814775094\times 10^{-16}i$ | $0.499999999999999i$ | $0.5i$               |
| $(N_t-1,N_x-1)$                 | $4.09024637044016i$                | $0.5i$               | $0.5i$               |

: 4-site hex


| $(t,x)$                         | direct                                    | SVD                  | QR                   |
|:-------------------------------:|:-----------------------------------------:|:--------------------:|:--------------------:|
| $(0,0)$                         | $-0.327481836324505+ 0.50599452028844 i$  | $0.484302339402678i$ | $0.5i$               |
| $(\frac{N_t}{2},\frac{N_x}{2})$ | $0.0874416589550673+ -0.751432957407041i$ | $0.458832124896434i$ | $0.500000000000001i$ |
| $(N_t-1,N_x-1)$                 | $2.11293747885892+ 3.03110534714241 i$    | $0.485228878987189i$ | $0.5i$               |

: perylene


:::{.callout-note}
## These calculations were done using the strategy shown in @sec-pidot-2 (non-iterative)
:::

:::

## Testing the Leapfrog convergence

:::{style='fontsize:80%'}

$$ \phi_x(t)\sim \mathcal{N}(0,\sqrt{\tilde U})$$

<style scoped>
table {
  font-size: 12px;
}
</style>


| $N_{\mathrm{md}}$ | direct              | SVD                 | QR                  |
|:-----------------:|:-------------------:|:-------------------:|:-------------------:|
| 10                | 0.15086045572215    | 0.150857105853643   | 0.150857105853635   |
| 20                | 0.033381596895282   | 0.0333837258207161  | 0.0333837258207055  |
| 30                | 0.014619381779692   | 0.0146207324705294  | 0.0146207324705436  |
| 40                | 0.00818625904403092 | 0.00818431470392156 | 0.00818431470390024 |
| 50                | 0.00522651421779941 | 0.00522638413412224 | 0.00522638413414356 |
| 60                | 0.00362109034726998 | 0.00362510486849388 | 0.00362510486848677 |
| 70                | 0.00265901663452084 | 0.00266143415928966 | 0.00266143415928255 |
| 80                | 0.00203898020489746 | 0.00203671513328274 | 0.00203671513326853 |
| 90                | 0.00160767284646468 | 0.00160874527817256 | 0.00160874527816546 |
| 100               | 0.00130065914231992 | 0.00130278793841754 | 0.00130278793843175 |

: $|\Delta H|$ for 4-sites $\beta=10,\ N_t=16,\ U=3$, traj. length = 2.15090145112179


| $N_{\mathrm{md}}$ | direct                | SVD                  | QR                   |
|:-----------------:|:---------------------:|:--------------------:|:--------------------:|
| 10                | 2.37216357459998e+161 | 2894.58645324208     | 2894.58645437868     |
| 20                | 6.45692168254581e+149 | 2.49715895137987     | 2.49715895136711     |
| 30                | 111.151758259419      | 9.82309017725242     | 9.82309017725137     |
| 40                | 452.885671769746      | 0.160439285386673    | 0.160439285386559    |
| 50                | 2.40009531127047e+159 | 2.20900236911348e-05 | 2.20900236342914e-05 |
| 60                | 1.28940361666192e+133 | 0.0116471152680333   | 0.011647115267948    |
| 70                | 275.052903624312      | 0.0248126318837194   | 0.0248126318836057   |
| 80                | 235.175670559966      | 0.0220153798488809   | 0.0220153798487104   |
| 90                | 2.73184806706786e+163 | 0.0170521637526519   | 0.0170521637527372   |
| 100               | 2.84399868278976e+155 | 0.0135074943290761   | 0.0135074943289339   |

: $|\Delta H|$ for 4-sites $\beta=90,\ N_t=128,\ U=3$, traj. length = 2.2813755026283

<!--
| 110               | 0.00107760782278277 | 0.0010765035876581  | 0.00107650358765099 |
-->

:::

## "Show me the money already!!!"

$$ \phi_x(t)\sim \mathcal{N}(0,\sqrt{\tilde U})$$

| $N_{\mathrm{md}}$ | direct             | SVD                | QR                 |
|:-----------------:|:------------------:|:------------------:|:------------------:|
| 10                | 13197.5599734183   | 12410.2152741463   | 12419.2583383426   |
| 20                | 0.336478338469675  | 0.336478209620793  | 0.336478209620793  |
| 30                | 0.139472862608244  | 0.139472812958672  | 0.139472812958786  |
| 40                | 0.086138119130112  | 0.0861381733492976 | 0.0861381733492976 |
| 50                | 0.0574682545507414 | 0.0574681171206066 | 0.0574681171206919 |
| 60                | 0.0405703254913021 | 0.0405702122974674 | 0.0405702122974105 |
| 70                | 0.0300749665267404 | 0.0300748554155916 | 0.0300748554155348 |
| 80                | 0.0231536000576966 | 0.0231536705274493 | 0.0231536705275346 |
| 90                | 0.0183609919218384 | 0.0183610492163098 | 0.0183610492162813 |
| 100               | 0.014910266950011  | 0.0149101994680052 | 0.0149101994679768 |

: $|\Delta H|$ for perylene $\beta=10,\ N_t=16,\ U=2$, traj. length = 1.75620368075343

| $N_{\mathrm{md}}$ | direct             | SVD                | QR                 |
|:-----------------:|:------------------:|:------------------:|:------------------:|
| 10                | N/A   | 99839.4   | 99817.8   |
| 20                | N/A  | 191.549  | 191.549  |
| 30                | N/A  | 0.932486  | 0.932486  |
| 40                | N/A  | 1.13841 | 1.13841 |
| 50                | N/A | 1.52342 | 1.52342 |
| 60                | N/A | 1.27622 | 1.27622 |
| 70                | N/A | 0.963409 | 0.963409 |
| 80                | N/A | 0.662005 | 0.662005 |
| 90                | N/A | 0.402434 | 0.402434 |
| 100               | N/A  | 0.202738 | 0.202738 |

: $|\Delta H|$ for perylene $\beta=90,\ N_t=256,\ U=2$, traj. length = 1.31715

## Speeding up the force calculation

:::{style='fontsize:80%'}

+  Unfortunately none of the recursive schemes proposed in @sec-pidot-1 and @sec-pidot-2 are stable

+  But as suggested by Johann and implemented earlier by Finn, the prefix/suffix scheme speeds things up considerably

+  One calculates 
   - all possible 'prefixes' $\Pi(t) = F_k(t).F_k(t-1)\ldots F_k(0)$
   - all possible 'suffixes' $\Sigma(t) = F_k(N_t-1).F_k(N_t-2)\ldots F_k(t)$
   - these calculations can be done recursively and thus fast, and requires $\mathcal{O}(2N_t V^2)$ memory (which is rougly 2 times more), but this is not an issue
   
+  The force at timeslice $t$ is simply $\dot\pi(t)=\left[1+\Pi(t).\Sigma(t+1)\right]^{-1}$
   - this calculation scales as $\mathcal{O}(N_t V^3)$
   - ***every aspect of this calculation is stable!***
   
:::

## Some plots of convergence

```{python}
#| label: fig-lf-convergence
#| fig-cap: 'Convergence of leapfrog algorithm for perylene system with $U=2,\mu=0,\beta=90$.  The initial configuration was sampled as $\phi\sim\mathcal{N}(0,\sqrt{\tilde U})$.'

import numpy as np
import matplotlib.pyplot as plt

Nmd = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200])
dH1 = np.array([21.8365,
       4.96144,
       2.17953,
       1.22433,
       0.783497,
       0.544007,
       0.399644,
       0.30596,
       0.241736,
       0.195801,
       0.161815,
       0.135967,
       0.115852,
       0.0998921,
       0.0870163,
       0.0764787,
       0.0677454,
       0.060427,
       0.0542334,
       0.0489455])

dH2 = np.array([53.4381884479317,
       13.2819894774439,
       5.89678399775585,
       3.31569757729994,
       2.12167825760116,
       1.47324881295935,
       1.08232537245931,
       0.828624799531099,
       0.654699335158512,
       0.530296869526865,
       0.438256010515033,
       0.368253038277544,
       0.313775251224797,
       0.270549408976876,
       0.23567740121689,
       0.20713748129856,
       0.183484473467615,
       0.163663148136038,
       0.146888450559345,
       0.13256655054829])

fig, ax = plt.subplots(1,2,sharey=True)
ax[0].plot(1/Nmd**2, dH1, '.')
ax[0].grid()
ax[0].set_ylabel(rf'$|\Delta H|$')
ax[0].set_xlabel(r'$1/N_{\mathrm{md}}^2$');
ax[0].set_xscale('log')
ax[0].set_yscale('log')
ax[0].set_title(r'$N_t=512$')
ax[1].plot(1/Nmd**2, dH2, '.')
ax[1].grid()
ax[1].set_xscale('log')
ax[1].set_yscale('log')
ax[1].set_xlabel(r'$1/N_{\mathrm{md}}^2$');
ax[1].set_title(r'$N_t=1024$')

plt.show()
```
